source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "minimal-mistakes-jekyll"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-archives"
gem "jekyll-paginate-v2"
gem "jekyll-gist"
gem "jekyll-include-cache"
gem "jekyll-scholar"
gem "jekyll-watch", "~> 2.2"
gem "kramdown", "~> 2.3"
gem "kramdown-parser-gfm"
gem "csv"
gem "base64"
gem "bigdecimal"
gem "tzinfo"
gem "tzinfo-data"
gem "webrick"
gem "faraday-retry"